# Peer-Reviewed Publications

-   Leelahapongsathon, K., Wongphruksasoong V., Vos, A., Kasemsuwan, S., **Kittisiam, T.**, Sagarasaeranee, O. & Chanachai, K. (2023). ‘Oral Vaccination of Dogs as a Complementary Tool for Canine Rabies Control: The Thai Protocol’, CABI Books. CABI International. <https://www.cabidigitallibrary.org/doi/full/10.1079/9781800622975.0010>

-   **Kittisiam, T.**, Phimpraphai, W., Kasemsuwan, S., & Thakur, K. K. (2021). Analyses of Contact Networks of Community Dogs on a University Campus in Nakhon Pathom, Thailand. *Veterinary Sciences*, *8*(12), 299. <https://doi.org/10.3390/vetsci8120299>

# Conference presentations, proceedings, and posters

\* = Presenter

-   **Kittisiam, T.**\*, Ritter, C., Morabito, E., Stacey, A., Khosa, D. & Jones-Bitton, A. (2023, May 31 - June 1). Measures of positive mental health in graduating veterinary students: findings from baseline data collection. \[Poster session\]. 16th Canadian Association of Veterinary Epidemiology and Preventive Medicine (CAVEPM) Conference 2023, Guelph, ON, Canada. [Link to conference proceedings](https://bpb-ca-c1.wpmucdn.com/sites.uoguelph.ca/dist/6/356/files/2023/05/CAVEPM-2023-Conference-Proceedings.pdf)

-   Morabito, E.\*, Jones-Bitton, A., **Kittisiam, T.**, Stacey, A., VanLeeuwen, J., Gunn McQuillan, H., Ritter, C. (2023, May 31 - June 1). Understanding meaningful work: conversations with early-career veterinarians across Canada.\[Oral Presentation\]. 16th Canadian Association of Veterinary Epidemiology and Preventive Medicine (CAVEPM) Conference 2023, Guelph, ON, Canada.

-   **Kittisiam, T.\***, Ritter, C., Morabito, E., Stacey, A., Khosa, D. & Jones-Bitton, A. (2023, May 18). Quantifying well-being, emotional intelligence, and resilience in graduating veterinary students: findings from baseline data collection. \[Oral presentation\]. Centre for Public Health and Zoonoses (CPHAZ) Symposium 2023, Guelph, ON, Canada.

-   **Kittisiam, T.\***, Ritter, C., Morabito, E., Stacey, A., Khosa, D. & Jones-Bitton, A. (2022, August 7-12). A longitudinal mixed-methods analysis of self-efficacy, emotional intelligence, and resilience in veterinary students transitioning into the veterinary profession. \[Poster session\]. 16th International Symposium of Veterinary Epidemiology and Economics (ISVEE), Halifax, NS, Canada. [Link to conference proceedings](https://venuewest-my.sharepoint.com/personal/congress_venuewest_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcongress%5Fvenuewest%5Fcom%2FDocuments%2FPublic%2FISVEE%202022%2FISVEE%2D2022%2DProceedings%2Epdf&parent=%2Fpersonal%2Fcongress%5Fvenuewest%5Fcom%2FDocuments%2FPublic%2FISVEE%202022&ga=1)

-   Morabito, E.\*, Jones-Bitton, A., **Kittisiam, T.**, Stacey, A., VanLeeuwen, J., Gunn McQuillan, H., Ritter, C. (2022, August 7-12). Quantitative assessment of Eudaimonia and Hedonia as protective factors on veterinary mental health in a longitudinal, Canada-wide study.  \[Oral Presentation\]. 16th International Symposium of Veterinary Epidemiology and Economics (ISVEE), Halifax, NS, Canada.

-   Wanakumjorn, P., **Kittisiam, T.\***, Sukitmongkolkul, J., Rumnum, J., Aungchayakul, T., Witoonsatian, K., Lertwatcharasarakul, P., Phatthanakunanan, S., Jala, S. (2019, June 13-14). Development of Loop-Mediated Isothermal Amplification to Detect Duck Enteritis Virus \[Conference presentation\]. KUVIC 2019, Prachuap Khiri Khan, Thailand. [Link to conference proceedings](https://drive.google.com/file/d/1yZRHZO7-HAir8yJzq7p4NUmUjO7IO5Td/view)
