---
title: "“A Multitude of Emotions” in Veterinary Work: A Mixed-Methods Analysis of Emotional Intelligence and Experiences in Early-Career Veterinarians"
---

### Tipsarp Kittisiam^1^, Emily Morabito^2^, Caroline Ritter^2^, Adam Stacey^3^, Deep Khosa^1^ and Andria Jones^1^

^1^ Ontario Veterinary College, University of Guelph.\
^2^ Atlantic Veterinary College, University of Prince Edward Island\
^3^ University of Saskatchewan

## Abstract

Emotions are integral to veterinary work. Despite rewarding experiences, veterinarians may also experience emotional distress, predisposing to burnout and possibly leaving the profession. Mastery of Emotional Intelligence (EI) has the potential to help veterinarians cope with emotional work demands, enhance teamwork, and improve client communication. Previous research suggests EI in veterinarians demonstrates opportunity for improvement. This study aimed to understand how validated measures of EI change throughout the first year of practice and describe early-career veterinarians’ experiences with managing intense emotions.

This study used mixed qualitative and quantitative methods. We conducted a longitudinal survey of the graduating Classes of 2022 and 2023 from the five veterinary schools in Canada, from graduation to 1-year in clinical practice (final time point: March 2024). The survey included the Trait Emotional Intelligence Questionnaire - Short form (TEIQue-SF) (range 1-7; higher scores reflect higher EI). Participants’ baseline (t1) (n=212) mean EI score (4.93, 95%CI 4.82 - 5.0-3) was marginally lower than the referent population (5.11, 95%CI 4.98 - 5.24). Cis-men and cis-women had higher EI scores than other genders (p=0.03). EI subscale analysis showed no difference in well- being and self-control, but marginally lower emotionality (5.04, 95%CI 4.90 - 5.17 vs. 5.25, 95%CI 5.11-5.39) and marginally higher sociability (5.39, 95%CI 5.24 - 5.54 vs. 4.97, 95%CI 4.84 - 5.1) than the referent population. Longitudinal modelling techniques will help determine how EI and its subscales change over time.\
Transcriptions of interviews with 21 early-career veterinarians (October 2022 – August 2023) are being thematically analyzed. Participants described the emotionally charged aspect of clinical work, acknowledged the importance of EI in practice, and shared pathways taken to improve their EI. Participants’ lived experiences acknowledge the benefits of EI on veterinarians’ clinical practice and well-being, highlight training gaps, and complement the opportunities for improving EI observed in the quantitative results.

## References

Bartram, D. J., Yadegarfar, G., & Baldwin, D. S. (2009). Psychosocial working conditions and work-related stressors among UK veterinary surgeons. *Occup Med (Lond)*, *59*(5), 334-341. <https://doi.org/10.1093/occmed/kqp072>

Brooks, J., McCluskey, S., Turley, E., & King, N. (2015). The Utility of Template Analysis in Qualitative Psychology Research. *Qual Res Psychol*, *12*(2), 202-222. <https://doi.org/10.1080/14780887.2014.955224>

Cake, M. A., Bell, M. A., Williams, J. C., Brown, F. J., Dozier, M., Rhind, S. M., & Baillie, S. (2016). Which professional (non-technical) competencies are most important to the success of graduate veterinarians? A Best Evidence Medical Education (BEME) systematic review: BEME Guide No. 38. *Med Teach*, *38*(6), 550-563. <https://doi.org/10.3109/0142159X.2016.1173662>

Creswell, J. W., & Poth, C. N. (2018). *Qualitative inquiry & research design : choosing among five approaches* (Fourth edition. ed.). SAGE Publications, Inc.

Darby, B. J., Watkins, S. T., Haak, P. P., Ravi-Caldwell, N., Bland, K., Bissett, C. J., Kryda, K. T., Murphy, J., Hungerford, L., & Russon, J. (2023). Veterinarians show resilience during COVID-19: challenges faced and successful coping strategies. *J Am Vet Med Assoc*, *261*(6), 888-897. <https://doi.org/10.2460/javma.22.12.0584>

Gardner, D. H., & Hini, D. (2006). Work-related stress in the veterinary profession in New Zealand. *N Z Vet J*, *54*(3), 119-124. <https://doi.org/10.1080/00480169.2006.36623>

Gilling, M. L., & Parkinson, T. J. (2009). The transition from veterinary student to practitioner: a "make or break" period. *J Vet Med Educ*, *36*(2), 209-215. <https://doi.org/10.3138/jvme.36.2.209>

Hatch, P. H., Winefield, H. R., Christie, B. A., & Lievaart, J. J. (2011). Workplace stress, mental health, and burnout of veterinarians in Australia. *Aust Vet J*, *89*(11), 460-468. <https://doi.org/10.1111/j.1751-0813.2011.00833.x>

Mastenbroek, N. J., van Beukelen, P., Demerouti, E., Scherpbier, A. J., & Jaarsma, A. D. (2015). Effects of a 1 year development programme for recently graduated veterinary professionals on personal and job resources: a combined quantitative and qualitative approach. *BMC Vet Res*, *11*, 311. <https://doi.org/10.1186/s12917-015-0627-y>

McArthur, M. L., Learey, T. J., Jarden, A., Van Gelderen, I., Hazel, S. J., Cake, M. A., Mansfield, C. F., Zaki, S., & Matthew, S. M. (2021). Resilience of veterinarians at different career stages: The role of self-efficacy, coping strategies and personal resources for resilience in veterinary practice. *Vet Rec*, *189*(12), e771. <https://doi.org/10.1002/vetr.771>

Perret, J. L., Best, C. O., Coe, J. B., Greer, A. L., Khosa, D. K., & Jones-Bitton, A. (2020). Prevalence of mental health outcomes among Canadian veterinarians. *J Am Vet Med Assoc*, *256*(3), 365-375. <https://doi.org/10.2460/javma.256.3.365>

Petrides, K. V. (2009a). Psychometric Properties of the Trait Emotional Intelligence Questionnaire (TEIQue). In J. D. A. Parker, D. H. Saklofske, & C. Stough (Eds.), *Assessing Emotional Intelligence* (pp. 85-101). Springer US. <https://doi.org/10.1007/978-0-387-88370-0_5>

Petrides, K. V. (2009b). Technical manual for the Trait Emotional Intelligence Questionnaires. In (1st ed.). London: London Psychometric Laboratory.

Platt, B., Hawton, K., Simkin, S., & Mellanby, R. J. (2012). Suicidal behaviour and psychosocial problems in veterinary surgeons: a systematic review. *Soc Psychiatry Psychiatr Epidemiol*, *47*(2), 223-240. <https://doi.org/10.1007/s00127-010-0328-6>

Scrucca, L. (2023). *Model-Based Clustering, Classification, and Density Estimation Using Mclust in R*. CRC Press.

Timmins, R. P. (2006). How does emotional intelligence fit into the paradigm of veterinary medical education? *J Vet Med Educ*, *33*(1), 71-75. <https://doi.org/10.3138/jvme.33.1.71>

VanderWeele, T. J., Chen, Y., Long, K., Kim, E. S., Trudel-Fitzgerald, C., & Kubzansky, L. D. (2020). Positive Epidemiology? *Epidemiology*, *31*(2), 189-193. <https://doi.org/10.1097/EDE.0000000000001147>
