---
title: "Emotional Intelligence, a Gap to Improve One Health Competencies"
date: 2025-11-25
categories:
- "Oral"
---

## Mentioned articles

-   ["A qualitative exploration of the emotional experiences and applications of emotional intelligence in early-career veterinarians"](https://bvajournals.onlinelibrary.wiley.com/doi/10.1002/vetr.5599)

-   [“This is my why.” Exploring the concept of meaningful work in early-career veterinarians across Canada](https://doi.org/10.3389/fvets.2025.1595949)

## References

Adin, D. B., Royal, K. D., & Adin, C. A. (2020). Cross-sectional assessment of the emotional intelligence of fourth-year veterinary students and veterinary house officers in a teaching hospital. *J Vet Med Educ*, *47*(2), 193-201. <https://doi.org/10.3138/jvme.0518-065r>

Bar-On, R. (2006). The Bar-On model of emotional-social intelligence (ESI). *Psicothema*, *18 Suppl*(Suppl), 13-25. <https://www.ncbi.nlm.nih.gov/pubmed/17295953>

Bartram, D. J., Yadegarfar, G., & Baldwin, D. S. (2009). A cross-sectional study of mental health and well-being and their associations in the UK veterinary profession. *Soc Psychiatry Psychiatr Epidemiol*, *44*(12), 1075-1085. <https://doi.org/10.1007/s00127-009-0030-8>

Bell, M. A., Cake, M. A., King, L. T., & Mansfield, C. F. (2022). Identifying the capabilities most important for veterinary employability using a modified Delphi process. *Vet Rec*, *190*(7), e777. <https://doi.org/10.1002/vetr.777>

Best, C. O., Perret, J. L., Hewson, J., Khosa, D. K., Conlon, P. D., & Jones-Bitton, A. (2020). A survey of veterinarian mental health and resilience in Ontario, Canada. *Can Vet J*, *61*(2), 166-172. <https://www.ncbi.nlm.nih.gov/pubmed/32020936>

Blokland, K., Coe, J. B., & Spitznagel, M. B. (2024). Veterinary team members experiencing high levels of burden transfer are more likely to report burnout and a less optimal psychosocial work environment. *J Am Vet Med Assoc*, *262*(3), 343-351. <https://doi.org/10.2460/javma.23.06.0354>

Cake, M. A., McArthur, M. M., Matthew, S. M., & Mansfield, C. F. (2017). Finding the balance: uncovering resilience in the veterinary literature. *J Vet Med Educ*, *44*(1), 95-105. <https://doi.org/10.3138/jvme.0116-025R>

Corrigan, V. K., Newman, R. L., Richmond, P., Strand, E. B., & Vaisman, J. M. (2024). The future of flourishing in veterinary medicine: a systems-informed positive psychology approach in veterinary education \[Review\]. *Front Vet Sci*, *11*, 1484412. <https://doi.org/10.3389/fvets.2024.1484412>

Fritschi, L., Morrison, D., Shirangi, A., & Day, L. (2009). Psychological well-being of Australian veterinarians. *Aust Vet J*, *87*(3), 76-81. <https://doi.org/10.1111/j.1751-0813.2009.00391.x>

Hatch, P. H., Winefield, H. R., Christie, B. A., & Lievaart, J. J. (2011). Workplace stress, mental health, and burnout of veterinarians in Australia. *Aust Vet J*, *89*(11), 460-468. <https://doi.org/10.1111/j.1751-0813.2011.00833.x>

Mayer, J. D., Salovey, P., Caruso, D. R., & Sitarenios, G. (2001). Emotional intelligence as a standard intelligence. *Emotion*, *1*(3), 232-242. [https://doi.org/10.1037//1528-3542.1.3.232](https://doi.org/10.1037/1528-3542.1.3.232)

Nett, R. J., Witte, T. K., Holzbauer, S. M., Elchos, B. L., Campagnolo, E. R., Musgrave, K. J., Carter, K. K., Kurkjian, K. M., Vanicek, C. F., O'Leary, D. R., Pride, K. R., & Funk, R. H. (2015). Risk factors for suicide, attitudes toward mental illness, and practice-related stressors among US veterinarians. *J Am Vet Med Assoc*, *247*(8), 945-955. <https://doi.org/10.2460/javma.247.8.945>

Perret, J. L., Best, C. O., Coe, J. B., Greer, A. L., Khosa, D. K., & Jones-Bitton, A. (2020). Prevalence of mental health outcomes among Canadian veterinarians. *J Am Vet Med Assoc*, *256*(3), 365-375. <https://doi.org/10.2460/javma.256.3.365>

Petrides, K. V. (2009). Psychometric properties of the Trait Emotional Intelligence Questionnaire (TEIQue). In J. D. A. Parker, D. H. Saklofske, & C. Stough (Eds.), *Assessing Emotional Intelligence* (pp. 85-101). Springer US. <https://doi.org/10.1007/978-0-387-88370-0_5>

Platt, B., Hawton, K., Simkin, S., & Mellanby, R. J. (2010). Systematic review of the prevalence of suicide in veterinary surgeons. *Occup Med (Lond)*, *60*(6), 436-446. <https://doi.org/10.1093/occmed/kqq044>

Platt, B., Hawton, K., Simkin, S., & Mellanby, R. J. (2012). Suicidal behaviour and psychosocial problems in veterinary surgeons: a systematic review. *Soc Psychiatry Psychiatr Epidemiol*, *47*(2), 223-240. <https://doi.org/10.1007/s00127-010-0328-6>

Schutte, N. S., Malouff, J. M., Hall, L. E., Haggerty, D. J., Cooper, J. T., Golden, C. J., & Dornheim, L. (1998). Development and validation of a measure of emotional intelligence. *Personality and Individual Differences*, *25*(2), 167-177. <https://doi.org/10.1016/S0191-8869(98)00001-4>

Wells, J., Watson, K., R, E. D., Siraj, A. Q. S., J, R. M., Verma, A., Sharma, M., & Nahar, V. K. (2021). Associations among stress, anxiety, depression, and emotional intelligence among veterinary medicine students. *Int J Environ Res Public Health*, *18*(8), 3934. <https://doi.org/10.3390/ijerph18083934>
